"""changed wallettype enum from investment to brokerage

Revision ID: ea3aa60a29db
Revises: 1260a771215c
Create Date: 2026-07-11 11:57:19.750016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3aa60a29db'
down_revision: Union[str, Sequence[str], None] = '1260a771215c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TYPE wallettype
        RENAME VALUE 'investment' TO 'brokerage';
        """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
