"""add debt wallet group and debt category type support

Revision ID: 1823deedc3cc
Revises: ea3aa60a29db
Create Date: 2026-07-16 09:10:25.771059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1823deedc3cc'
down_revision: Union[str, Sequence[str], None] = 'ea3aa60a29db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
    ALTER TYPE walletgroup
    ADD VALUE 'debt';
    """)

    op.execute("""
    ALTER TYPE categorytype
    ADD VALUE 'debt';
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
