"""add name column to transactions table and added set default values for its columns

Revision ID: 2ea4b06af863
Revises: d96e2e741feb
Create Date: 2026-07-10 11:02:50.935124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ea4b06af863'
down_revision: Union[str, Sequence[str], None] = 'd96e2e741feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('transactions', 'description',
            existing_type=sa.VARCHAR(length=400),
            nullable=True)
    op.alter_column('transactions', 'status',
            existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'CANCELLED', 'FAILED', name='transactionstatus'),
            server_default='COMPLETED',
            existing_nullable=False)
    op.alter_column('transactions', 'is_recurring',
            existing_type=sa.BOOLEAN(),
            server_default='false',
            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'CANCELLED', 'FAILED', name='transactionstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    op.drop_column('transactions', 'name')
    # ### end Alembic commands ###
