"""added wallet_group column to wallets table

Revision ID: 1260a771215c
Revises: 4017331ce0d8
Create Date: 2026-07-10 15:55:29.109043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1260a771215c'
down_revision: Union[str, Sequence[str], None] = '4017331ce0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    wallet_group = sa.Enum(
    'available',
    'savings',
    'emergency_fund',
    'investment',
    'unassigned',
    name='walletgroup'
)

    wallet_group.create(op.get_bind(), checkfirst=True)

    op.add_column('wallets', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('wallets', sa.Column('wallet_group', sa.Enum('available', 'savings', 'emergency_fund', 'investment', 'unassigned', name='walletgroup'), server_default='available', nullable=False))
    
    op.execute("""

    CREATE TYPE wallettype_new AS ENUM (
    'cash',
    'bank',
    'credit_card',
    'crypto',
    'investment',
    'other'
    );
    """)

    op.execute("""
        ALTER TABLE wallets
        ALTER COLUMN type
        TYPE wallettype_new
        USING type::text::wallettype_new;
    """)

    op.execute("DROP TYPE wallettype;")

    op.execute("""
        ALTER TYPE wallettype_new
        RENAME TO wallettype;
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'wallet_group')
    op.drop_column('wallets', 'is_default')
    # ### end Alembic commands ###
