"""add deleted_at column to users table

Revision ID: 7a20eb2ee31a
Revises: a4c6365a64fb
Create Date: 2026-07-09 11:35:41.218902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a20eb2ee31a'
down_revision: Union[str, Sequence[str], None] = 'a4c6365a64fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_users', 'deleted_at')
    # ### end Alembic commands ###
